apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bluepod
  name: bluepod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluepod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bluepod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
      tolerations:
      - key: "color"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}