apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
- apiGroups: [""]  
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list","create", "delete","describe"]
- apiGroups: [""]  
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list","create", "delete","describe"]