  GNU nano 6.2                                            /root/nginx-pod.yaml *                                                    
apiVersion: v1 
kind: Pod 
metadata:
  name: nginx 
spec:
  schedulerName: my-scheduler
  containers:  
  - image: nginx
    name: nginx