---
apiVersion: rbac.authorization.k8s.io/vibetal
kind: ClisterRoleBiding
metadata:
  creationTimestamp: null
  name: nginx-ingress-admin
  namespace: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRol
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: nginx-ingress
  namespace: nginx-ingress
...

