apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1001
    capabilities:
        add: ["SYS_TIME"]
  containers:
  -  image: ubuntu
     name: web
     command: ["sleep", "5000"]
     securityContext:
      runAsUser: 1002
      capabilities:
        add: ["SYS_TIME", "OTHER"]

  -  image: ubuntu
     name: sidecar
     command: ["sleep", "5000"]